const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET
const CLOUDINARY_POST = 'reality-code/post'
const CLOUDINARY_MESSAGE = 'reality-code/message'
const CLOUDINARY_SECTION = 'reality-code/section'

module.exports = {
    CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET,
    CLOUDINARY_POST,
    CLOUDINARY_MESSAGE,
    CLOUDINARY_SECTION
}